### ISSUE TITLE
summary and CFP translation 

### ISSUE THREAD

**Issue by dracher** [dracher/qecamp-2020#15]
- [ ] content/updates/2019-07-25.cn.md
- [ ] [pls see the new content in english version](https://github.com/open-testcon/website_src/blob/f0177d2952b24a6a783783bf47a59fadc1978109/data/cn/homepage/data.toml#L15)

@stuartchuan

**Comment by stuartchuan** [comment]
Resolved by https://github.com/open-testcon/website_src/pull/16
