### ISSUE TITLE
Tracks and footer translation

### ISSUE THREAD

**Issue by shi2wei3** [dracher/qecamp-2020#8]
@stuartchuan Please help to translate the tracks and the footer of the website into Chinese and add Chen Shi as reviewer, @SCHEN2015 please help to review the PR from Chuan Yu, @dracher please help to guide @stuartchuan which file contain these content under translation, welcome to add more things if i missed.

**Comment by dracher** [comment]
- [x] [homepage](https://github.com/open-testcon/website_src/blob/master/data/en/homepage/data.toml)
- [x] [footer](https://github.com/open-testcon/website_src/blob/master/data/en/footer/data.toml)

translated version should put under `cn` folder with identical data structure, same hierarchy.

**Comment by dracher** [comment]
@stuartchuan sorry, i forgot to update `homepage data cn data.toml` , please pull and submit PR again

**Comment by stuartchuan** [comment]
@dracher does the en version of footer ready to translate to cn?

**Comment by dracher** [comment]
@stuartchuan not sure what suppose to be listed in footer section yet, waiting for @shi2wei3 decision

**Comment by dracher** [comment]
no translation needed for footer
